version: "3.8"
services:
  storage:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8085
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service_db:5432/storage_db
    container_name: storage
    ports:
      - "8086:8086"
    depends_on:
      - service_db
  service_db:
    image: postgres:14.7-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - /var/lib/docker/containers/booking/db/data:/var/lib/postgresql/data
    ports:
      - "5439:5432"
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data: