app:
  db:
    url: jdbc:postgresql://0.0.0.0:5439/storage_db
    username: postgres
    password: postgres
spring:
  application:
    name: s-storage-service
  main:
    banner-mode: off
  datasource:
    url: ${app.db.url}
    username: ${app.db.username}
    password: ${app.db.password}
    driver-class-name: org.postgresql.Driver
server:
  port: 8086
  servlet:
    context-path: /chat

logging:
  level:
    org:
      springframework: ERROR
      hibernate: ERROR
      apache: ERROR
    kz:
      aldi: DEBUG
