app:
  postgres:
    url: jdbc:postgresql://0.0.0.0:5432/storage_db
    username: test
    password: test
  minio:
    url: http://localhost:9000
    username: root
    password: rootroot
    bucket: common
    streaming:
      default-chunk-size: 3145728
spring:
  application:
    name: s-storage-service
  main:
    banner-mode: off
  datasource:
    url: ${app.postgres.url}
    username: ${app.postgres.username}
    password: ${app.postgres.password}
    driver-class-name: org.postgresql.Driver
minio:
  url: ${app.minio.url}
  access:
    name: ${app.minio.username}
    secret: ${app.minio.password}
  bucket:
    name: ${app.minio.bucket}
  put-object-part-size: 5242880

server:
  port: 8086
cxf:
  path: /Service
logging:
  level:
    org:
      springframework: ERROR
      hibernate: ERROR
      apache: ERROR
    kz:
      company: DEBUG
